name: ci-v12
on:
    push:
        tags:
            - 'v*'
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: 
                run: ['stacks/sugar12/php80-local-build.yml']
        steps:
            - run: sudo sysctl -w vm.max_map_count=262144
            - run: echo '127.0.0.1 docker.local' | sudo tee -a /etc/hosts
            - uses: actions/checkout@v1
            - run: cp -r ./tests/web_tests ./data/app/sugar/
            - run: ./tests/start.sh ${{ matrix.run }}
            - run: ./tests/web_tests.sh ${{ matrix.run }} 12.0 8.0
            - run: ./tests/stop.sh ${{ matrix.run }}

    docker:
        strategy:
            fail-fast: false
            matrix:
                include:
                - dockercontext: ./images/php/80/apache
                  image: sugarcrmdevelopers/sugardockerized
                  prefix: php8.0-apache-
                - dockercontext: ./images/php/80/cron
                  image: sugarcrmdevelopers/sugardockerized
                  prefix: php8.0-cron-
                - dockercontext: ./images/mysql/80
                  image: sugarcrmdevelopers/sugardockerized
                  prefix: mysql8.0-
        runs-on: ubuntu-latest
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
          - name: Set up QEMU
            uses: docker/setup-qemu-action@v2
          - name: Set up Docker Buildx
            uses: docker/setup-buildx-action@v2
          - name: Login to DockerHub
            if: ${{ github.repository == 'sugarcrm-developers/SugarDockerized' }}
            uses: docker/login-action@v2
            with:
                username: ${{ secrets.DOCKERHUB_USERNAME }}
                password: ${{ secrets.DOCKERHUB_TOKEN }}
          - name: Extract metadata (tags, labels) for Docker
            id: meta
            uses: docker/metadata-action@v4
            with:
                images: ${{ matrix.image }}
                flavor: |
                    latest=true
                    prefix=${{ matrix.prefix }},onlatest=true

          - name: Build and push
            uses: docker/build-push-action@v4
            with:
                context: ${{ matrix.dockercontext }}
                push: ${{ github.repository == 'sugarcrm-developers/SugarDockerized' && 'true' || 'false' }}
                platforms: 'linux/amd64,linux/arm64'
                tags: ${{ steps.meta.outputs.tags }}
                labels: ${{ steps.meta.outputs.labels }}
